// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      clean: {
        build: {
          src: ['build']
        }
      },
      coffee: {
        app: {
          expand: true,
          cwd: 'src',
          src: ['**/*.coffee'],
          dest: 'build',
          ext: '.js'
        }
      },
      readme_generator: {
        porcupine: {
          options: {
            readme_folder: '_readme',
            output: 'README.md',
            table_of_contents: true,
            toc_extra_links: [],
            generate_changelog: false,
            banner: 'banner.md',
            has_travis: false,
            generate_footer: true,
            generate_title: true,
            package_title: null,
            package_name: null,
            package_desc: null,
            informative: true
          },
          order: {
            'intro.md': 'intro',
            'installation.md': 'Installation'
          }
        }
      },
      watch: {
        app: {
          files: '**/*.coffee',
          tasks: ['coffee']
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-readme-generator');
    grunt.registerTask('build', ['clean:build', 'coffee', 'readme_generator:porcupine']);
    return grunt.registerTask('default', 'build');
  };

}).call(this);
