define ->
  AUTO_DETECT_RENDERER: 'AUTO_DETECT_RENDERER'

  # event names
  COMPONENT_ADDED: 'COMPONENT_ADDED'
  COMPONENT_REMOVED: 'COMPONENT_REMOVED'
  COMPONENT_STATE_CHANGED: 'COMPONENT_STATE_CHANGED'
  ENTITY_ADDED: 'ENTITY_ADDED'
  ENTITY_REMOVED: 'ENTITY_REMOVED'
  SYSTEM_ADDED: 'SYSTEM_ADDED'
  SYSTEM_REMOVED: 'SYSTEM_REMOVED'
  SYSTEM_ACTIVATED: 'SYSTEM_ACTIVATED'
  GAME_PAUSED: 'GAME_PAUSED'
  GAME_RESUMED: 'GAME_RESUMED'
  GAME_STATE_SAVED: 'GAME_STATE_SAVE'

  # priority defaults
  Priority:
    preUpdate: 1
    update: 2
    move: 3
    collisionResolving: 4
    stateMachine: 5
    animate: 6
    render: 7